apiVersion: v1
data:
  .dockerconfigjson: eyJhdXRocyI6eyI5eGh5bWd5ei5ncmE3LmNvbnRhaW5lci1yZWdpc3RyeS5vdmgubmV0Ijp7InVzZXJuYW1lIjoiaXNtYWlsLmphbGxvdWxpIiwicGFzc3dvcmQiOiIxOTg4U2ZheDAyMDIiLCJlbWFpbCI6ImlzbWFpbC5qYWxsb3VsaUBpbGV4LWludGVybmF0aW9uYWwuY29tIiwiYXV0aCI6ImFYTnRZV2xzTG1waGJHeHZkV3hwT2pFNU9EaFRabUY0TURJd01nPT0ifX19
kind: Secret
metadata:
  creationTimestamp: "2022-06-07T07:22:24Z"
  name: secret-ids
  namespace: test-docker-auth
  resourceVersion: "24732037956"
  uid: cb0fb1aa-62fc-4062-a48b-2bba62e4539a
type: kubernetes.io/dockerconfigjson
---
apiVersion: v1
kind: Pod
metadata:
  name: ids
  namespace: test-docker-auth
spec:
  containers:
  - name: ids
    image: 9xhymgyz.gra7.container-registry.ovh.net/ilex-international/idsphere/ids-web@sha256:d05e0c5ea69a3cda911ba342b4e824e7800d4ec57ec82232b09238ab9249f845
  imagePullSecrets:
  - name: secret-local-saasv2
