apiVersion: v1
data:
  ssl.cert: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURJekNDQWd1Z0F3SUJBZ0lVYmF6WU9Tdzk1dUtZdEppVURnc0xSRTRsYUowd0RRWUpLb1pJaHZjTkFRRUwKQlFBd0lURWZNQjBHQTFVRUF3d1dhSFIwY0hNdGFXeGxlQzVsZUdGdGNHeGxMbU52YlRBZUZ3MHlNakEyTWpBeApPREUzTURSYUZ3MHlNekEyTVRVeE9ERTNNRFJhTUNFeEh6QWRCZ05WQkFNTUZtaDBkSEJ6TFdsc1pYZ3VaWGhoCmJYQnNaUzVqYjIwd2dnRWlNQTBHQ1NxR1NJYjNEUUVCQVFVQUE0SUJEd0F3Z2dFS0FvSUJBUUNuM2hnQzJhd1kKRExzNDk0bHUvS2RTYUZkaGNtbnYvVUNhUEpzL0pRNzZsNTg5c3d3WHNLMUduR0R0Q0Y1dStWeXh5bGdVUnFUWQpaU2xRZDBDVk1zc0d5cGYxOVViMkt0bTd2d3dtQTRveVkvWWNKOHVndm1uM1lMNnpQRURydHlvY014WmdERlhvCktRSUlJSmFkOHI0MnF3NjlvZm9wQVZZQUREZVowV3lXeXhJVmsyRWYrZ0kxdThFZks3b0h1RkhOZC9WVGhOc04KdDBIN3p6MkR2cEFjSURPTTM2YVJ3YXBwUFRZdDFTM0ZQZ2VJcWtvVGRDN215RkI4SHYxR2dSbURJZXFtVGkybQpOWnVDRWd3Rk9lc3B3NEUzQTBQQVgyc2llKy9SZFgzYk5HTGZSTDNlZHpCVklyVi9Vb0hodzdaeWM3YjVTMzJSCkJLNlQrZnVIQjgyMUFnTUJBQUdqVXpCUk1CMEdBMVVkRGdRV0JCVHZsNC9LcXlTRndzaDE3QXBERXBVRVZCZEwKZXpBZkJnTlZIU01FR0RBV2dCVHZsNC9LcXlTRndzaDE3QXBERXBVRVZCZExlekFQQmdOVkhSTUJBZjhFQlRBRApBUUgvTUEwR0NTcUdTSWIzRFFFQkN3VUFBNElCQVFDYzB0VUc2M1o2TDZRMGhwYW9lREYvdmYzdUJueDB4cUFPCnhTTmk3NjQweDNZNHlvdjFyNHFDUGhwM0xBNzJFMWFZZWdBUzRQS0dvM0owMGJVY29TUFNsRGVYdG4zNW5EQ0UKRTN5dStDZXQ5eTdzL1hMdHRBWkE5QU5GWHJnbkdOTUNOS1JqVVZVUmhUNTd4aGVjR01PLytqbWVvNWRtdGk3QwpBUnh4YW1mZklwY0hXSlB3Y0FpSWVKd21ob1NFOVJWeEdHR2VJRXRNRHdxcU1oOTR6WWZLbWx1MnFiU0g3ZXg5ClRwRVVDYWFmREtpZStJeHlRLzVmd1E4eHBnOVZjMWFXTDBiUTVkVHdYSTVjbG95UkFaaXBWajNhR0M2d0d5QTUKRkRCQVNoT20zSUFpbHB6citOT0o3elA5VUp1bm1lbXFkTXFpeDlpckFObVcwVzY5dGJoMAotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
  ssl.key: LS0tLS1CRUdJTiBSU0EgUFJJVkFURSBLRVktLS0tLQpNSUlFcEFJQkFBS0NBUUVBcDk0WUF0bXNHQXk3T1BlSmJ2eW5VbWhYWVhKcDcvMUFtanliUHlVTytwZWZQYk1NCkY3Q3RScHhnN1FoZWJ2bGNzY3BZRkVhazJHVXBVSGRBbFRMTEJzcVg5ZlZHOWlyWnU3OE1KZ09LTW1QMkhDZkwKb0w1cDkyQytzenhBNjdjcUhETVdZQXhWNkNrQ0NDQ1duZksrTnFzT3ZhSDZLUUZXQUF3M21kRnNsc3NTRlpOaApIL29DTmJ2Qkh5dTZCN2hSelhmMVU0VGJEYmRCKzg4OWc3NlFIQ0F6ak4rbWtjR3FhVDAyTGRVdHhUNEhpS3BLCkUzUXU1c2hRZkI3OVJvRVpneUhxcGs0dHBqV2JnaElNQlRucktjT0JOd05Ed0Y5ckludnYwWFY5MnpSaTMwUzkKM25jd1ZTSzFmMUtCNGNPMmNuTzIrVXQ5a1FTdWsvbjdod2ZOdFFJREFRQUJBb0lCQUIvYjRNYTV0UldqWk96OAozZEo0bFBEbzZKeVA4RmNodzE4Q1haeHdWaFZ0TFVXeWMzc1RodTg5d285NTVTSStwVDhBM2hLTERjSWNBT2xLCm1MRTRRSnY3V3pmTTR6alpEUlc2dm4yQWNudjV5TDJ6Tjh3OEZ6Umg0ZzkyUWdQNmNUMkUzSnhCK3hQaXBJWVMKV1VPRXpHRG51aFozWlZqZTdnbDRTQjBqUis2ZU1RelpyZGhGNGlvSXhrcWxSUzNndjZUN0VZdTFDcVBUaC90NQpGV3RqTFkyTlhIclcyaW5xVERZbGZXYzZ2VDR6MG92eVJEQXNkR0ZGV1lMM3JBUWlRdUtuSnNRRlRiSzhYd0xBCmEyWkxEbDg2L2s2NkQraE52UnpDN0lWbCt3RUhmTjNady9zZGxpSGJ4OUhrb25zei8wZ3Q5YWJUTlZQQWZVL24KTGV6cGs4a0NnWUVBMUVqT0ZGMktZdFIxN1QyemtOdXJETEUraEtsTWJBaFMxWjd5TCt1TDZnMDRCS2FoMGdJVAorRlJwS2UrMS96VmVqU29GQ3ozendVMEI1MDBkL0gzUmczMUxHMTlycEFSckxOWXNXRUVDZTRUcVdTQm84QS9aClp6YTBaV1hyc3Z0VDBwdzlOUEtuSVMwakhFWGROczhqc2NLU2xidS9YUHFGZHFCVGxEODVpbThDZ1lFQXltKzUKZ3ppQUh0TnhYMlhuVHNYQ3BpNVNhbmx0eG5vaFh1d3MyaUV1RDJIZ0NETndKMGtTaTVWdWJEa0R0elVxbGxNdgpZNy9MZ0F4Q0Y5WXdQVUlTeFUwM2pyVVVlYjNuaW1TYzFxaTFvYndlZkpBY283OFB6Y2VpOWVTaUI2YzVwUnJDCkF4UUovaUF0MVNBQ1pYWmJKQUpqVmVvWEF4ZzFnMFlzajU2WERCc0NnWUVBbmZRK1FyRUhVMW83RlBlZ01OMEMKZlVNMC9ZanJNRWRSTzFvMVlxcWxSTlhwSkt6SUkzY2dYTnFTRlg0anNXMkltUWozRDlKZEdTdXZpdWU2dERENgpRQmh1VmtPOTJDRGhqazhlVjl5bmVEa0NGcWNpN2QwZEtzdHRselVyRjlZaUhNZmNVeFZxZmlrVHd1bkpIQXNzCnlBdTYvbWJna05KbmxFamZaNk5Uc1VrQ2dZQTcybmErUG9sYkUrZFVibnZLaFp3OHFEdUQ4YTBzWHRYWkMvbGkKOFNaK005RWFlNkx3YXFHS0ZiK1ZUZkkwVEFyd2NWMzBuek9iQTRUVEtXZ1A1S1pLSWIrSWVTKzVveFYvaktuMgpxZUV5RmIzcDFHNHpWLzFqT1dDTVZYSTIweEd2S0U4dXU5RU1peFVpQzVuSnlBbkFodGc2QWNHV0Q2VmF6L2ZDCjZ2Lzcrd0tCZ1FESHJhb29NKzkvTTBkQzNKaXZSeFBUaWsrQ2VEeTdMam9qZnZSSUJ4QXVWZXd3NUw3d2hGS3IKUUluUE05R0NXNHlJeW5hUjExbXA4NHY5OTR1Q2NwcmwrdW4yYVFueWM2cytUd0ZUOGEvU3kxVUhKVW1FR3JyWgpYY2pLVS9UeEVHaUpLbjYvZWtVNlYyV1JwVzZqalZkS0RGUVhNWnovS1JvODBMT0xnUUM4TGc9PQotLS0tLUVORCBSU0EgUFJJVkFURSBLRVktLS0tLQo=
kind: Secret
metadata:
  name: ssl-key-cert
  namespace: app-docker-space
type: Opaque
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rancher-hello-world
  namespace: app-docker-space
  labels:
    app: rancher-hello-world
spec:
  selector:
    matchLabels:
      app: rancher-hello-world
  replicas: 2
  template:
    metadata:
      labels:
        app: rancher-hello-world
    spec:
      containers:
      - name: rancher-hello-world
        image: rancher/hello-world
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: rancher-hello-world-svc
  namespace: app-docker-space
spec:
  selector:
    app: rancher-hello-world
  ports:
    - port: 8088
      targetPort: 80
  type: LoadBalancer
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: hello-world-ing
  namespace: app-docker-space
  annotations:
    kubernetes.io/ingress.class: "nginx"
spec:
  tls:
  - hosts:
    - https-ilex.example.com
    secretName: ssl-key-cert
  rules:
  - host: https-ilex.example.com
    http:
      paths:
      - path: /rancher
        pathType: Prefix
        backend:
          service:
            name: rancher-hello-world-svc
            port:
              number: 8088
